### ISSUE TITLE
Enhancement request: optionally, only pass through message on state change

### ISSUE THREAD

**Issue by colinl** [DeanCording/node-red-contrib-state-machine#2]
Dean, if you were working on this node a useful enhancement for me would be an option to only pass input messages through when the state has changed.  Unless I am missing something in the features to allow this. At the moment I have to use a change node to clear the topic then an rbe.

**Comment by DeanCording** [comment]
Option added in Version 1.1.0

**Comment by colinl** [comment]
Great, thanks.
