### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cflurin** [DeanCording/node-red-contrib-state-machine#5]
Hi,
I've tried your state-machine node and see some useful use cases.
One feature I'd like is to pass the input msg for all `node-input-statePropertyType` so I'd always be able to use the output for triggering other nodes.

I commented these lines in "state-machine.html":
```js
/*
            if ($("#node-input-statePropertyType").val() == "msg") {
                node.outputs = 1;
            } else {
                node.outputs = 0;
            }
*/
```
It works for me and I'd appreciate if you could add this feature.

**Comment by cflurin** [comment]
Any chance of an answer?

**Comment by DeanCording** [comment]
I'm not quite sure what you are trying to achieve here.  If the state-machine is not adding the state to the msg then you can just have the state-machine node in parallel with other nodes that take the same input.

**Comment by cflurin** [comment]
I use this feature to trigger other nodes:

**_At any time, the node can only be in one of the defined states and it will only transition to another state when it receives a trigger defined for the current state._**

When using flow/global properties there is no output so I have to add nodes like `change node` to achieve the same functionality.

![state-machine1](https://user-images.githubusercontent.com/5056710/40535618-dbb15baa-6009-11e8-9913-451166e055f2.jpeg)

If the output is always available, I can set the flow/global property in the state-machine node and avoid the use of an additional node.

![state-machine2](https://user-images.githubusercontent.com/5056710/40535829-86e613e4-600a-11e8-9339-e3b59c1f7905.jpeg)

Anyway I don't see any disadvantages if the output is always available, it can remain unused.

Take a look at the `change node`, you can set flow/global properties but the output is always available.
